### ISSUE TITLE
Realtime spying for debug mode

### ISSUE THREAD

**Issue by ganoro** [sterlingw/SimpleSpy.js#1]
It would be great if I can do something like:

``` javascript
function realFoo(arg) {
   runFirstAlgorithm(arg);
   thenRunAnother(arg);
}
var foo = spyOn(realFoo, true);
foo();
```

See the true parameter when dispatching spyOn()
The output of this programs 
realFoo called runFirstAlgorithm() with arg
realFoo called thenRunAnother() with arg

**Comment by sterlingw** [comment]
> The output of this programs 
> realFoo called runFirstAlgorithm() with arg
> realFoo called thenRunAnother() with arg

Logging functions the spy calls doesn't seem like the spy's responsibility. You can easily read the source of `realFoo`.

If you still want log the functions `realFoo` calls, you can achieve that. Perhaps you can create a decorator like this:

```
var foo = logCalls(realFoo);

foo(); // calls realFoo, logging "called runFirstAlgorithm" and "called thenRunAnother()"
```

Hope that helps :smiley:
